services:
 backend2:
  build: /backend_2_repo
  volumes:
   - ./backend_2_repo:/app/
  ports:
    - 8000:8000

  tty: true

 mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#  mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#     # to login to DB via container's user/bin/mongosh: mongosh -u="root" -p="example"
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/