services:
 backend1:
  build: 
    context: /backend_1_repo
    dockerfile: Dockerfile
  volumes:
   - ./backend_1_repo:/app/
  ports:
    - 5000:5000
    - 5678:5678
  depends_on:
   - redis
   - mongo
  tty: true

 frontend:
  build:
    context: /backend_1_repo/frontend
    dockerfile: Dockerfile.dev
  volumes:
   - ./backend_1_repo/frontend/src:/app/src
   - ./backend_1_repo/frontend/index.html:/app/index.html
   - ./backend_1_repo/frontend/vite.config.js:/app/vite.config.js
  ports:
    - 5173:5173
  tty: true