services:
 backend1:
  build: /backend_1_repo
  working_dir: /app/ # or add "WORKDIR /app/" in Dockerfile instead
  volumes:
   - ./backend_1_repo:/app/
  ports:
    - 5000:5000

  tty: true

 backend2:
  build: /backend_2_repo
  working_dir: /app/ # or add "WORKDIR /app/" in Dockerfile instead
  volumes:
   - ./backend_2_repo:/app/
  ports:
    - 8000:8000

  tty: true

 mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

 mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/