services:
 backend1:
  build: /backend_1_repo
  working_dir: /app/ # or add "WORKDIR /app/" in Dockerfile instead
  volumes:
   - ./backend_1_repo:/app/
  ports:
    - 5000:5000

  tty: true
 frontend:
  build:
    context: .
    dockerfile: /backend_1_repo/frontend/Dockerfile.prod
    
  tty: true