services:
 backend1:
  build:
    context: /backend_1_repo
    dockerfile: Dockerfile.prod
  ports:
    - 5000:5000

  tty: true

 frontend:
  build:
    context: .
    dockerfile: /backend_1_repo/frontend/Dockerfile.prod
  ports:
    - 8080:8080
    
  tty: true