services:
 backend1:
  build:
    context: /backend_1_repo
    dockerfile: Dockerfile
  ports:
    - 5000:5000
  depends_on:
   - redis
   - mongo
  tty: true

 frontend:
  build:
    context: .
    dockerfile: /backend_1_repo/frontend/Dockerfile.prod
  ports:
    - 8080:8080
  tty: true