FROM node as build-step

WORKDIR /app

COPY frontend .

RUN npm install

RUN npm run build

FROM python:3.9-slim

WORKDIR /app

COPY --from=build-step app/static/index.html ./frontend/static/index.html

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY backend1.py .
ENTRYPOINT ["python", "backend1.py"]