FROM node as build-step

WORKDIR /app

# COPY backend_1_repo/frontend/package.json .
COPY backend_1_repo/frontend .

RUN npm install

RUN npm run build

# COPY . .

FROM nginx

COPY --from=build-step app/static /usr/share/nginx/html

COPY nginx.conf /etc/nginx/