FROM node as build-step

WORKDIR /app

COPY backend_1_repo/frontend/package.json .

RUN npm install

COPY backend_1_repo/frontend .

RUN npm run build

# COPY . .

# FROM nginx

# COPY --from=build-step /hello/static /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/