FROM node as build-step

WORKDIR /app

COPY backend_1_repo/frontend .

RUN npm install

RUN npm run build

FROM nginx

COPY --from=build-step app/static /usr/share/nginx/html/static/frontend

COPY nginx.conf /etc/nginx/